#!/bin/bash

GIT_ROOT=/data/daris/services/git
WEB_ROOT=/data/daris/users/mflux/gitstats-web

export MFLUX_HOME=/opt/mflux
export MFLUX_HOST=$(hostname)
export MFLUX_PORT=8443
export MFLUX_TRANSPORT=HTTPS
export MFLUX_DOMAIN=system
export MFLUX_USER=manager
export MFLUX_PASSWORD_ENC=R3Vlc3NfbWU4Cg==
export MFLUX_UMASK=0007
MFCOMMAND=/data/local/mediaflux/bin/mfcommand

APP_NAME=gitstats
APP_NAMESPACE=/www/${APP_NAME}
APP_LABEL=${APP_NAME}
APP_URL=/${APP_NAME}

# index.html
echo "<html>" > ${WEB_ROOT}/index.html
echo "<head><title>GIT STATS</title></head>" >> ${WEB_ROOT}/index.html
echo "<frameset cols=\"15%,85%\">" >> ${WEB_ROOT}/index.html
echo "<frame src=\"frame_left.html\" name=\"frame_left\"/>" >> ${WEB_ROOT}/index.html
echo "<frame src=\"frame_right.html\" name=\"frame_right\" />" >> ${WEB_ROOT}/index.html
echo "<noframes>" >> ${WEB_ROOT}/index.html
echo "<h2>Your browser does not handle frames!</h2>" >> ${WEB_ROOT}/index.html
echo "</noframes>" >> ${WEB_ROOT}/index.html
echo "</frameset>" >> ${WEB_ROOT}/index.html
echo "</html>" >> ${WEB_ROOT}/index.html

# frame_right.html
DATE_TIME=$(date +'%H:%M:%S %d-%b-%Y')
echo "<html>" > ${WEB_ROOT}/frame_right.html
echo "<h3>GIT STATS</h3>" >> ${WEB_ROOT}/frame_right.html
echo "<p>Select one of the repositories in the left side to view its statistical results generated by gitstats.</p>" >> ${WEB_ROOT}/frame_right.html
echo "<p><b>Last update:</b> $(date +'%H:%M:%S %d-%b-%Y')</p>" >> ${WEB_ROOT}/frame_right.html
echo "</html>" >> ${WEB_ROOT}/frame_right.html

# frame_left.html
echo "<html><base target=\"frame_right\"><h3>GIT Repositories:</h3><ul>" > ${WEB_ROOT}/frame_left.html
for REPO in $(ls -d $GIT_ROOT/*)
do
    WEB_REPO=${WEB_ROOT}/$(basename ${REPO})
    WEB_REPO=${WEB_REPO%.*}
    NAME_REPO=$(basename ${WEB_REPO})
    mkdir -p ${WEB_REPO}; rm -fr ${WEB_REPO}/*; gitstats $REPO ${WEB_REPO}
    echo "<li><a href=\"${NAME_REPO}/index.html\">${NAME_REPO}</a></li>" >> ${WEB_ROOT}/frame_left.html
done
echo "</ul></html>" >> ${WEB_ROOT}/frame_left.html

$MFCOMMAND logon $MFLUX_DOMAIN $MFLUX_USER $(echo $MFLUX_PASSWORD_ENC | base64 -d)
$MFCOMMAND "asset.query :where namespace>=$APP_NAMESPACE :action pipe :service -name asset.destroy"
$MFCOMMAND asset.import :namespace -create true $APP_NAMESPACE :update true :label -create true $APP_LABEL :label PUBLISHED :url file:${WEB_ROOT}
$MFCOMMAND http.processor.destroy :app ${APP_NAME} :url ${APP_URL}
$MFCOMMAND "http.processor.create :app ${APP_NAME} :url ${APP_URL} :type asset :translate ${APP_NAMESPACE} :entry-point index.html"
$MFCOMMAND logoff
