#!/bin/bash

[[ -z $(which java) ]] && echo "Java is not found." >&2 && exit 1

JAR=$(dirname $0)/daris-client.jar
[[ ! -f $JAR ]] && echo "${JAR} is not found." >&2 && exit 2

java -cp $JAR daris.client.cli.DicomIngestCLI ${1+"$@"}